version: 0.2
phases:
    install:
        commands:
            - echo "AWS_REGION" $AWS_REGION
            - echo "CODEBULID_BUILD_ARN" $CODEBULID_BUILD_ARN
            - echo "CODEBUILD_BUILD_ID" $CODEBUILD_BUILD_ID
            - echo "CODEBUILD_BUILD_IMAGE" $CODEBUILD_BUILD_IMAGE
            - echo "CODEBUILD_INITIATOR" $CODEBUILD_INITIATOR
            - echo "CODEBUILD_RESOLVED_SOURCE_VERSION" $CODEBUILD_RESOLVED_SOURCE_VERSION
            - echo "CODEBUILD_SOURCE_REPO_URL" $CODEBUILD_SOURCE_REPO_URL
            - echo "CODEBUILD_SOURCE_VERSION" $CODEBUILD_SOURCE_VERSION
    pre_build:
        commands:
            - echo "pre build commands here"
    build:
        commands:
            - echo "build commands here"
artifacts:
    files:
        - output/**/*
