[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  revision = "e2323b8f3943f429985baf9f56dd3c2aeabd0e83"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.8"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
