service: opolis-build

provider:
  name: aws
  runtime: go1.x
  profile: opolis
  region: us-west-2
  stage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  build:
    handler: bin/build
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: build
          method: post
