service: opolis-build

provider:
    name: aws
    runtime: go1.x
    profile: opolis
    region: ${opt:region, self:custom.defaultRegion}
    stage: ${opt:stage}
    cfLogs: true

custom:
    defaultRegion: us-west-2

package:
    exclude:
        - ./**
    include:
        - ./bin/**

functions:
    listener:
        handler: bin/listener
        memorySize: 128
        timeout: 10
        role: lambdaRole
        environment:
            EVENT_TABLE:
                Ref: dynamoTable
        events:
            - http:
                path: event
                method: post
    builder:
        handler: bin/builder
        memorySize: 128
        timeout: 300
        role: lambdaAllRole
        environment:
            ARTIFACT_STORE:
                Ref: artifactBucket
        events:
            - stream:
                type: dynamodb
                arn:
                    Fn::GetAtt:
                      - dynamoTable
                      - StreamArn
    notifier:
        handler: bin/notifier
        memorySize: 128
        timeout: 30
        role: lambdaAllRole
        events:
            - cloudwatchEvent:
                event:
                    source:
                        - "aws.codepipeline"
                    detail-type:
                        - "CodePipeline Stage Execution State Change"
                    detail:
                        state:
                            - STARTED
                            - SUCCEEDED
                            - FAILED
    s3deployer:
        handler: bin/lib/s3deployer
        memorySize: 128
        timeout: 300
        role: lambdaS3DeployerRole
    s3cleaner:
        handler: bin/lib/s3cleaner
        memorySize: 128
        timeout: 300
        role: lambdaAllRole
    stack-cleaner:
        handler: bin/lib/stack-cleaner
        memorySize: 128
        timeout: 300
        role: lambdaAllRole

resources:
    Resources:
        # override log group retention policy
        ListenerLogGroup:
            Properties:
                RetentionInDays: 30
        BuilderLogGroup:
            Properties:
                RetentionInDays: 30
        NotifierLogGroup:
            Properties:
                RetentionInDays: 30
        S3deployerLogGroup:
            Properties:
                RetentionInDays: 30
        S3cleanerLogGroup:
            Properties:
                RetentionInDays: 30
        artifactBucket:
            Type: AWS::S3::Bucket
            Properties:
                AccessControl: Private
                BucketName:
                    'Fn::Join':
                        - "-"
                        - - "Ref": "AWS::StackName"
                          - "artifact-store"
        dynamoTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                KeySchema:
                - AttributeName: id
                  KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 3
                    WriteCapacityUnits: 3
                StreamSpecification:
                    StreamViewType: NEW_IMAGE
                TimeToLiveSpecification:
                    AttributeName: ttl
                    Enabled: true
        lambdaAllRole:
            Type: AWS::IAM::Role
            Properties:
                Path: "/"
                RoleName: opolis-build-lambda-all
                AssumeRolePolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                        - lambda.amazonaws.com
                      Action:
                        - sts:AssumeRole
                Policies:
                    - PolicyName: root
                      PolicyDocument:
                          Version: '2012-10-17'
                          Statement:
                          - Effect: Allow
                            Action: '*'
                            Resource: '*'
        lambdaRole:
            Type: AWS::IAM::Role
            Properties:
                Path: "/"
                RoleName: opolis-build-lambda
                AssumeRolePolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                        - lambda.amazonaws.com
                      Action:
                        - sts:AssumeRole
                Policies:
                    - PolicyName: root
                      PolicyDocument:
                          Version: '2012-10-17'
                          Statement:
                          - Effect: Allow
                            Action:
                              - logs:CreateLogGroup
                              - logs:CreateLogStream
                              - logs:PutLogEvents
                            Resource:
                                - "arn:aws:logs:*:*:log-group:/aws/lambda/*:*:*"
                          - Effect: Allow
                            Action: ssm:GetParameter
                            Resource:
                                - "arn:aws:ssm:*:*:parameter/opolis-build-token"
                                - "arn:aws:ssm:*:*:parameter/opolis-build-hmac"
                          - Effect: Allow
                            Action: kms:Decrypt
                            Resource:
                                - "arn:aws:kms:*:*:key/344d9fba-07d2-45c8-9bde-2356aaedc6c3"
                          - Effect: Allow
                            Action: dynamodb:*
                            Resource:
                                - "Fn::Join":
                                    - "/"
                                    - - "arn:aws:dynamodb:*:*:table"
                                      - "Ref": "dynamoTable"
                                - "Fn::Join":
                                    - "/"
                                    - - "arn:aws:dynamodb:*:*:table"
                                      - "Ref": "dynamoTable"
                                      - "stream/*"
        lambdaS3DeployerRole:
            Type: AWS::IAM::Role
            Properties:
                Path: "/"
                RoleName: opolis-build-lambda-s3-deployer
                AssumeRolePolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                        - lambda.amazonaws.com
                      Action:
                        - sts:AssumeRole
                Policies:
                    - PolicyName: root
                      PolicyDocument:
                          Version: '2012-10-17'
                          Statement:
                          - Effect: Allow
                            Action: logs:*
                            Resource:
                                - "arn:aws:logs:*:*:*"
                          - Effect: Allow
                            Action:
                                - codepipeline:PutJobSuccessResult
                                - codepipeline:PutJobFailureResult
                            Resource: '*'
                          - Effect: Allow
                            Action: s3:*
                            Resource: '*'
